// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvsakwoxsuzjroupnvcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2c2Frd294c3V6anJvdXBudmNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDE2ODcsImV4cCI6MjA2NjU3NzY4N30.vceGU32HfKTccZUSH6fFRmO6o2e-tKnEnUpEJGV4-R0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);